# Here we define our services.
# We have two services: db and storemanager.

services:
  # The db service is used to create a MySQL database container. It will be used by the storemanager service to store the Products data.
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD:  123456
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: lm
      MYSQL_PASSWORD: lmpw
    volumes:
      - db_data:/var/lib/mysql

# The storemanager service is used to create a Spring Boot application container. It will handle the Products data and Secyrities.
  storemanager:
    container_name: StoreManager
    build:
      context: ./lm-app
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysqldb"
      - "SPRING_DATASOURCE_USERNAME=lm"
      - "SPRING_DATASOURCE_PASSWORD=lmpw"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data: