version: "3.8"   # Specifica la versione di Docker Compose da utilizzare

#Definizione dei servizi che verranno eseguiti all'interno di container indipendenti
#I servizi sono app (SpringBoot) e mysqldb (MySQL Database)
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped  # Specifica la politica di riavvio del container, viene riavviato solo se non è stato arrestato manualmente
    #env_file: ./.env         # Specifica il file .env da cui leggere le variabili d'ambiente
    environment:             # Specifica le variabili d'ambiente da prendere dal file .env
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=lm_db
    ports:                   # Specifica le porte da utilizzare per il servizio
      #- $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT   # NOTA: le due porte LOCAL_PORT e DOCKER_PORT sono diverse per evitare conflitti
      - 27017:7002
    volumes:                 # Specifica i volumi da montare nel container
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb              #Indica l'ordine di avvio dei servizi, in questo caso il servizio app dipende dal servizio mysqldb
    build: ./lm-app    # Specifica la directory in cui si trova il Dockerfile per la build dell'immagine
    restart: on-failure
    #env_file: ./.env
    ports:
      - 8080:7001
    environment:
      # Specifica le variabili d'ambiente che la nostra app SpringBoot utilizzerà
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:7002/lm_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true  # Specifica se il container deve essere eseguito in modalità interattiva
    tty: true         # Specifica se il container deve essere eseguito in modalità pseudo-TTY

volumes:
  db: