server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:world}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:dbpassword}
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.lm.SpringSecLogin

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.lm.SpringSecLogin: INFO

jwt:
  secretKey: secret
  issuer: lm
  expirationMinute: 10

swagger:
  contact-name: Luca Eugenio Corrado & Marco Francesco Sette
  contact-url: ${SWAGGER_CONTACT_URL:https://www.unimore.it/it}
  app-name: ${SWAGGER_APP_NAME:SpringSecLogin}
  app-description: "SpringSecLogin is a simple login backend in Spring Boot. This project includes Spring Boot, Spring Data JPA, Spring Validation, Spring Security + JWT Token, MySQL, Mapstruct, Lombok, Swagger, Actuator and more."
  app-version: ${SWAGGER_APP_VERSION:2.0.0}
  app-license-url: ${SWAGGER_APP_LICENSE_URL:https://www.opensource.org/licenses/MIT}
  app-license: ${SWAGGER_APP_LICENSE:MIT}